(require 'diminish)

(diminish 'cider-mode  "𝕔")
;; (diminish 'cider-repl-mode  "ℂ")
(diminish 'clj-refactor-mode "♺")
;; (diminish 'clojure-mode  "λ")
;; (diminish 'clojure-test-mode  "λt")
(diminish 'color-identifiers-mode  "I")
(diminish 'eldoc-mode  "ℯ")
;; (diminish 'emacs-lisp-mode  "ℰ")
(diminish 'flyspell-mode  "✓")
;(diminish 'git-gutter+-mode  "⇌")
(diminish 'hs-minor-mode "⏦")
(diminish 'magit-auto-revert-mode  "☆")
(diminish 'my-keys-minor-mode  "⌨")
(diminish 'paredit-mode  "☾")
(diminish 'undo-tree-mode  "↶")
(diminish 'volatile-highlights-mode  "ℏ")
(diminish 'yas-minor-mode  "✂")
