(require 'diminish)

(diminish 'cider-mode  "λ𝕔")
(diminish 'company-mode  "ℂ")
(diminish 'clj-refactor-mode "♺")
(diminish 'color-identifiers-mode  "I")
(diminish 'eldoc-mode  "ℯ")
(diminish 'flyspell-mode  "✓")
(diminish 'hs-minor-mode "⏦")
(diminish 'magit-auto-revert-mode  "☆")
(diminish 'my-keys-minor-mode  "⌨")
(diminish 'paredit-mode  "☾")
(diminish 'undo-tree-mode  "↶")
(diminish 'volatile-highlights-mode  "ℏ")
(diminish 'yas-minor-mode  "✂")
